### ISSUE TITLE
Numerical Precision

### ISSUE THREAD

**Issue by bmershon** [bmershon/d3-equidecompose#4]
To everyone, and Chris especially, what are some thoughts on ways to mitigate the numerical precision issues? I see a few things to take into account:
- The **scale** of the polygons we operate on. If a polygon with a side of 20 px comes in the pipeline, should that be handled the same as one with a side length of 4,269 pixels?
- **Rotations** of polygons to place them in a bounding box. This seems to introduce more error. Should the actual geometry of the input polygons and derived cuts be operated on, or should bounding boxes and "exact" shapes like rectangles represented by their dimensions rather than their vertices be used when possible.
- Any ideas on what information should be produced/preserved from the*\* triangle-rectangle*\* and **rectangle-rectangle** cuts? Are their other ways of performing these cuts involving a "unit length side" for the canonical rectangle?

At the end of the day, I was wondering if there is a way push issues from numerical precision to the end of the pipeline. Part of my confusion is coming from what seems to be at least two different ways to approach the decomposition of a triangle to another triangle, based on reading Chris's notes and a [Wikipedia](https://en.wikipedia.org/wiki/Wallace%E2%80%93Bolyai%E2%80%93Gerwien_theorem) article.

**Comment by ctralie** [comment]
Hi Brooks,
That's a good question about the scale.  The dynamic range of the size of the pieces that you an get probably will be quite large, so you have to be careful

I'm not sure what you mean about rotations of polygons placing them inside of a bounding box.  But I like the idea of trying to keep track of exact things instead of storing intermediate vertices, when possible.  When I coded this up, I actually made new vertices for new pieces, but it might be better to see if you can find a way to do it that stores the cuts implicitly until the end where you need to use the Sutherland Hodgman algorithm or something else to make smaller pieces.  I definitely had issues with numerical precision at that step
